# kinematic: two_wheel_steering
type: 2FWS2RWD
geometry:
  axles_distance: 2.0
  front_axle:
    wheels_distance: 1.0
    wheels:
      radius: 0.32
      width: 0.2
      hub_carrier_offset: 0.02
  rear_axle:
    wheels_distance: 1.0
    wheels:
      radius: 0.32
      width: 0.2
      hub_carrier_offset: 0.02
  aabb:
    length: 2.6
    width: 1.09
    height: 1.5
    center: [0., 0., 1.2]
  ground_clearance: 0.45

front_wheels_steering_control:
  command:
    maximal_angle: 1.04
    maximal_angular_speed: 0.2433
  sensor:
    angle_std: 0.017453
    angle_range: 0.73

rear_wheels_speed_control:
  command:
    maximal_speed: 3.0
    maximal_acceleration: 1.0
  sensor:
    speed_std: 0.1
    speed_range: 3.0

inertia:
  mass: 800.
  center: [-0.1, 0.0, 0.2]
  z_moment: 0.

control_point: [-1.0, 0.0, 0.0]

joints:
  base_footprint_joint_name: base_footprint_joint
  inertial_joint_name: initial_joint
  front_left_wheel_steering_joint_name: front_left_wheel_steering_joint
  front_right_wheel_steering_joint_name: front_right_wheel_steering_joint
  front_left_wheel_spinning_joint_name: front_left_wheel_spinning_joint
  front_right_wheel_spinning_joint_name: front_right_wheel_spinning_joint
  rear_left_wheel_spinning_joint_name: rear_left_wheel_spinning_joint
  rear_right_wheel_spinning_joint_name: rear_right_wheel_spinning_joint

links:
  base_link_name: base_link
  base_footprint_link_name: base_footprint
  inertial_link_name: initial_link
  front_left_wheel_steering_link_name: front_left_wheel_steering_link
  front_right_wheel_steering_link_name: front_right_wheel_steering_link
  front_left_wheel_spinning_link_name: front_left_wheel_spinning_link
  front_right_wheel_spinning_link_name: front_right_wheel_spinning_link
  rear_left_wheel_spinning_link_name: rear_left_wheel_spinning_link
  rear_right_wheel_spinning_link_name: rear_right_wheel_spinning_link

deadzone_handler:
  # type: gaussian_noise
  # std_dev: 0.03

  type: dithering
  size: 0.04
  quantization_size: 0.04


