/**:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mobile_base_controller_fat:
      type: romea_mobile_base_controllers/MobileBaseController2FWS4WD

    mobile_base_controller_slim:
      type: romea_mobile_base_controllers/MobileBaseController2FWS2RWD
